# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '78fe8dfea80bddbe30ff00f1aa978f40'
  config.secret_key = '6e81b32c3c08e188616b2b6d9709379d'
  config.default_from = 'nans.noel@gmail.com'

end
