# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '78fe8dfea80bddbe30ff00f1aa978f40'
  config.secret_key = '95fe98e541d3ebe317f9418409886099'
  config.default_from = 'nans.noel@gmail.com'

end
